// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmboobarpveoamyyhqrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtYm9vYmFycHZlb2FteXlocXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzM2NzksImV4cCI6MjA3MDQ0OTY3OX0.yLBrRHGDiOYq3A9GqJNhJrg8RSly5ctD1lb9FTOA-9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});